// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-progress.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-progress.ts
var list_progress_default = defineTool({
  name: "list_progress",
  title: "List saved progress keys",
  description: "List all VISIBLE7 methodology progress entries (keys and last update time) saved by the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_progress").select("data_key, updated_at").eq("user_id", ctx.getUserId()).order("data_key");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-progress.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.23.8";
var get_progress_default = defineTool2({
  name: "get_progress",
  title: "Get saved progress",
  description: "Read the stored value of one VISIBLE7 progress entry (e.g. a phase's saved form data) for the signed-in user.",
  inputSchema: {
    data_key: z.string().trim().min(1).describe("Progress key, as returned by list_progress.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data_key }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_progress").select("data_key, data_value, updated_at").eq("user_id", ctx.getUserId()).eq("data_key", data_key).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No progress saved for key "${data_key}".` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/save-progress.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.23.8";
var save_progress_default = defineTool3({
  name: "save_progress",
  title: "Save progress",
  description: "Create or overwrite one VISIBLE7 progress entry for the signed-in user. The value must be JSON matching what the app stores under that key.",
  inputSchema: {
    data_key: z2.string().trim().min(1).describe("Progress key to write."),
    data_value: z2.string().min(1).describe("JSON-encoded value to store for this key.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ data_key, data_value }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let parsed;
    try {
      parsed = JSON.parse(data_value);
    } catch {
      return { content: [{ type: "text", text: "data_value must be valid JSON." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_progress").upsert(
      { user_id: ctx.getUserId(), data_key, data_value: parsed },
      { onConflict: "user_id,data_key" }
    ).select("data_key, updated_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? { data_key }) }],
      structuredContent: { entry: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/get-subscription.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_subscription_default = defineTool4({
  name: "get_subscription",
  title: "Get subscription status",
  description: "Read the signed-in user's VISIBLE7 subscription status, trial dates and access expiry.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subscriptions").select("status, trial_started_at, trial_ends_at, access_until, promo_code_used, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No subscription record found." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { subscription: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "antxexuffsuoyryghaey";
var mcp_default = defineMcp({
  name: "visible7-new",
  title: "visible7-new",
  version: "0.1.0",
  instructions: "Tools for VISIBLE7 MICEK, a 7-step online business methodology app. Use `list_progress` and `get_progress` to read the signed-in user's saved phase data (vision, ideation, strategy, implementation, benchmarking, launch, expansion), `save_progress` to write a phase entry, and `get_subscription` to check their access level. All tools act as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_progress_default, get_progress_default, save_progress_default, get_subscription_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
